[[events]]
name = "press"
event_type = "EV_KEY"
key_state = "pressed"
keys = ["BTN_RIGHT", "BTN_LEFT"]
command = "./loop_jitter.sh"

[[events]]
name = "released"
event_type = "EV_KEY"
key_state = "released"
keys = ["BTN_LEFT"]
command = "killall loop_jitter.sh"
